# Generated by Django 2.0.2 on 2018-03-23 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('length', models.DurationField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixlist.Mix')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=25, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('favorites', models.ManyToManyField(blank=True, to='mixlist.Mix')),
                ('following', models.ManyToManyField(blank=True, related_name='_profile_following_+', to='mixlist.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('extra_info', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='playlistmembership',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixlist.Track'),
        ),
        migrations.AddField(
            model_name='mix',
            name='playlist',
            field=models.ManyToManyField(through='mixlist.PlaylistMembership', to='mixlist.Track'),
        ),
        migrations.AddField(
            model_name='mix',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to='mixlist.Profile'),
        ),
        migrations.AddField(
            model_name='externallink',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mixlist.Track'),
        ),
    ]
