# Generated by Django 2.0.2 on 2018-03-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='provider',
            field=models.CharField(choices=[('SPOTIFY', 'Spotify'), ('SOUNDCLOUD', 'SoundCloud'), ('APPLEMUSIC', 'Apple Music'), ('YOUTUBE', 'YouTube'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
