# Generated by Django 2.0.2 on 2018-03-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('extra_info', models.CharField(max_length=100)),
                ('reference_count', models.IntegerField()),
                ('links', models.ManyToManyField(to='mixlist.ExternalLink')),
            ],
        ),
    ]
