# Generated by Django 2.0.2 on 2018-03-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixlist', '0002_externallink_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='playlist',
            field=models.ManyToManyField(to='mixlist.Track'),
        ),
        migrations.AddField(
            model_name='mix',
            name='slug',
            field=models.SlugField(default='diplo_year_end_mix_2013'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mix',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='mix',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
