# Generated by Django 2.0.2 on 2018-03-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixlist', '0003_auto_20180313_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='extra_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
