# Generated by Django 2.0.2 on 2018-03-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixlist', '0005_mix_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mix',
            name='artist',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
