# Generated by Django 2.0.2 on 2018-03-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixlist', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_following_+', to='mixlist.Profile'),
        ),
    ]
