# Generated by Django 2.0.2 on 2018-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixlist', '0006_auto_20180327_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
