# Generated by Django 2.0.2 on 2018-03-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixlist', '0007_auto_20180321_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='mixlist.Mix'),
        ),
    ]
