# Generated by Django 2.0.3 on 2018-04-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixlist', '0009_auto_20180415_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_profile_following_+', to='mixlist.Profile'),
        ),
    ]
