# Generated by Django 2.0.2 on 2018-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixlist', '0012_auto_20180419_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recentPlayed',
            field=models.ManyToManyField(blank=True, related_name='listeners', to='mixlist.Mix'),
        ),
    ]
